// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmTb-12Kgunpg_ZaaoWrLcq48581jt6VU',
    appId: '1:695452556806:web:d5e407e4c9e5c4a119ad87',
    messagingSenderId: '695452556806',
    projectId: 'thinkflow-1b602',
    authDomain: 'thinkflow-1b602.firebaseapp.com',
    storageBucket: 'thinkflow-1b602.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLJb5V-n03aV1kOPWYCmhlHw_WxAJ27f0',
    appId: '1:695452556806:android:bfd46027604ac6a719ad87',
    messagingSenderId: '695452556806',
    projectId: 'thinkflow-1b602',
    storageBucket: 'thinkflow-1b602.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPNUlnRDVycNb-JxTUytiEMAZXlA0-8oI',
    appId: '1:695452556806:ios:b7dc150b0e0ca75c19ad87',
    messagingSenderId: '695452556806',
    projectId: 'thinkflow-1b602',
    storageBucket: 'thinkflow-1b602.firebasestorage.app',
    iosBundleId: 'com.example.thinkflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPNUlnRDVycNb-JxTUytiEMAZXlA0-8oI',
    appId: '1:695452556806:ios:b7dc150b0e0ca75c19ad87',
    messagingSenderId: '695452556806',
    projectId: 'thinkflow-1b602',
    storageBucket: 'thinkflow-1b602.firebasestorage.app',
    iosBundleId: 'com.example.thinkflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmTb-12Kgunpg_ZaaoWrLcq48581jt6VU',
    appId: '1:695452556806:web:cc1bb53d92ede7d619ad87',
    messagingSenderId: '695452556806',
    projectId: 'thinkflow-1b602',
    authDomain: 'thinkflow-1b602.firebaseapp.com',
    storageBucket: 'thinkflow-1b602.firebasestorage.app',
  );
}
